
## 异常
异常 的特殊对象来管理程序执行期间发生的错误。每当发生让Python不知所措的错误时，它都会创建一个异常对象。

如果编写了处理该异常的代码，程序将继续运行；如果未对异常进行处理，程序将停止并显示traceback，其中包含有关异常的报告。

python中异常使用try-except 代码块处理的，即便出现异常，程序也将继续运行，显示自定义编写的友好的错误消息，而不是令用户迷惑的traceback。如果try 代码块中的代码运行起来没有问题，Python将跳过except 代码块；如果try 代码块中的代码导致了错误，Python将查找与之匹配的except 代码块并运行其中的代码

```python
try:
    print(5/0)
except ZeroDivisionError:
    print("You can't divide by zero!")
```

* 静默失败：Python有一个pass 语句，程序在发生异常时保持静默
```python
try:
    print(5/0)
except ZeroDivisionError:
    pass
```

* else 代码块，依赖try 代码块成功执行的代码都应放到else 代码块中
```python
try:
    # snip
except:
    # snip
else:
    # snip
```

## 异常分类
* ZeroDivisionError 异常：不能用数除以0
* FileNotFoundError 异常